galaxy_info:
  author: oasis_roles
  description: >-
    Creates or modifies Ceph OSD pools
  company: Red Hat, Inc.
  license: GPLv3
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 7
        - 8

  galaxy_tags:
    - oasis

dependencies: []
