# role tasks
- name: Set platform/version specific variables
  include_vars: "{{ __rolename_vars_file }}"
  loop:
    - "{{ ansible_facts.os_family }}.yml"
    - "{{ ansible_facts.distribution }}.yml"
    - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_major_version }}.yml"
    - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_version }}.yml"
  vars:
    __rolename_vars_file: "{{ role_path }}/vars/{{ item }}"
  when: __rolename_vars_file is file

- name: Install ceph-ansible package
  become: true
  become_user: "{{ prepare_adm_become_user }}"
  package:
    name: "{{ prepare_adm_packages }}"
    state: present

- block:
    - name: Copy local inventory file to system if it exists
      include_role:
        name: oasis_roles.system.upload_files
      vars:
        upload_files:
          - src: "{{ prepare_adm_inventory_file }}"
            dest: "{{ prepare_adm_destination }}/hosts"
            owner: "{{ prepare_adm_target_user }}"
            group: "{{ prepare_adm_target_group }}"
            mode: 0644
      when:
        - prepare_adm_inventory_file is not none
        - prepare_adm_inventory_file is file

    - name: Create list of group_vars files
      set_fact:
        _prepare_adm_group_vars: "{{ ( _prepare_adm_group_vars | default([]) ) + [{'src': item, 'dest': prepare_adm_destination + '/group_vars/' + (item | basename), 'owner': prepare_adm_target_user, 'group': prepare_adm_target_group, 'mode': '0644'}] }}"
      with_fileglob:
        - "{{ prepare_adm_group_vars_dir }}/*"

    - name: Copy local group_vars files to destination
      include_role:
        name: oasis_roles.system.upload_files
      vars:
        upload_files: "{{ _prepare_adm_group_vars }}"
  vars:
    upload_files_become: "{{ prepare_adm_become }}"
    upload_files_become_user: "{{ prepare_adm_become_user }}"

- become: "{{ prepare_adm_become }}"
  become_user: "{{ prepare_adm_become_user }}"
  block:
    - name: >
        Copy /usr/share/ceph-ansible/site.yml.sample to
        /usr/share/ceph-ansible/site.yml
      copy:
        remote_src: true
        src: /usr/share/ceph-ansible/site.yml.sample
        dest: /usr/share/ceph-ansible/site.yml
        owner: root
        group: root
        mode: 0644

    - name: Configure remote ansible.cfg
      ini_file:
        path: "{{ prepare_adm_destination }}/ansible.cfg"
        section: defaults
        option: "{{ item.key }}"
        value: "{{ item.value }}"
        create: true
        mode: u+rw
      with_dict: "{{ prepare_adm_ansible_cfg }}"

    - name: Create remote log directory
      file:
        path: "{{ prepare_adm_ansible_cfg.log_path | dirname }}"
        state: directory
        mode: 0755
        owner: "{{ prepare_adm_target_user }}"
        group: "{{ prepare_adm_target_group }}"
      when: "'log_path' in prepare_adm_ansible_cfg"

    - name: Configure /usr/share/ceph-ansible/ansible.cfg
      ini_file:
        path: /usr/share/ceph-ansible/ansible.cfg
        section: defaults
        option: "{{ item.key }}"
        value: "{{ item.value }}"
        create: true
        mode: u+rw
      with_dict: "{{ prepare_adm_ansible_cfg }}"
