# role tasks
- name: Set platform/version specific variables
  include_vars: "{{ __rolename_vars_file }}"
  loop:
    - "{{ ansible_facts.os_family }}.yml"
    - "{{ ansible_facts.distribution }}.yml"
    - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_major_version }}.yml"
    - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_version }}.yml"
  vars:
    __rolename_vars_file: "{{ role_path }}/vars/{{ item }}"
  when: __rolename_vars_file is file

- become: "{{ ceph_inventory_become }}"
  become_user: "{{ ceph_inventory_become_user }}"
  block:
    - name: Ensure that {{ ceph_inventory_destination | dirname }} exists
      file:
        path: "{{ ceph_inventory_destination | dirname }}"
        state: directory
        owner: "{{ ceph_inventory_owner }}"
        group: "{{ ceph_inventory_group }}"
        mode: o+rwx

    - name: Write a ceph-ansible compatible inventory
      template:
        src: ceph_inventory.j2
        dest: "{{ ceph_inventory_destination }}"
        mode: o+rw
