galaxy_info:
  author: oasis_roles
  description: >-
    Prepares a node to serve as the "adm" base for a Red Hat
    Ceph Storage system
  company: Red Hat, Inc.
  license: GPLv3
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 7
        - 8

  galaxy_tags:
    - oasis

dependencies: []
